### ISSUE TITLE
Missing ShapeNet test data (.pcd files)

### ISSUE THREAD

**Issue by wangyida** [wentaoyuan/pcn#37]
Hi Wentao, 

Thanks for your contribution to point cloud completion. I’m quite interested in your work PCN on 3DV. Currently, I am testing visually on ShapeNet based on your approach 'PCN'. I found that the test folder containing 'partial' and 'complete files are missing, together with a test.list file. Can you have a check here https://drive.google.com/drive/folders/1Y_tx3lrA2ivvM-bGxRO-TvbVBE8HoNPu on your google drive?

**Comment by wentaoyuan** [comment]
They have been uploaded. Please use the updated drive link in README.
