### ISSUE TITLE
The pointcloud sampled from CADs has inner structure.

### ISSUE THREAD

**Issue by SkyeFromKindergarten** [wentaoyuan/pcn#38]
Thanks for your work, I'v learned a lot.
I have a question, I run the code sample/mesh_sampling, and I get pointclouds of a car with inner structure. Isn't it unreasonable? Because our input is the surface of a partical car and the ground truth shouldn't be a car with inner structure. Is there any step I did wrong?

Looking for reply
Best regards.

**Comment by wentaoyuan** [comment]
Point clouds represent surfaces of objects. The interior of a car is a surface just like the exterior. Indeed, some of the car meshes in ShapeNet include the interior surfaces.
