### ISSUE TITLE
Installation of OpenEXR

### ISSUE THREAD

**Issue by SarahChane98** [wentaoyuan/pcn#50]
Hi! I'm currently exploring the render/process_exr.py codes and I need to install OpenEXR but I cannot build it from source. Can someone who has successfully installed OpenEXR before offer some tips on how to install it? Many thanks!!

**Comment by Leerw** [comment]
```bash
sudo apt-get install libopenexr-dev
pip install OpenEXR
```
I used this command and successfully installed OpenEXR, you can try it.

**Comment by SarahChane98** [comment]
Hi thank you for your help! Unfortunately I do not have root access but I managed to install it in another way.
