### ISSUE TITLE
There is an error in render/render_depth.py when I use it to generate the partial point cloud.

### ISSUE THREAD

**Issue by qinglew** [wentaoyuan/pcn#56]
```
Traceback (most recent call last):
  File "/media/rico/BACKUP/Dataset/ShapeNet/ShapeNetCoreV1/render_depth.py", line 91, in <module>
    scene, camera, output = setup_blender(width, height, focal)
  File "/media/rico/BACKUP/Dataset/ShapeNet/ShapeNetCoreV1/render_depth.py", line 76, in setup_blender
    bpy.data.objects['Cube'].select = True
AttributeError: 'Object' object has no attribute 'select'
```

What's the version of the Blender you used?

**Comment by peng666** [comment]
In the latest version, you can use 'bpy.data.objects['Cube'].select_set(True)'.

**Comment by peng666** [comment]
> ```
> Traceback (most recent call last):
>   File "/media/rico/BACKUP/Dataset/ShapeNet/ShapeNetCoreV1/render_depth.py", line 91, in <module>
>     scene, camera, output = setup_blender(width, height, focal)
>   File "/media/rico/BACKUP/Dataset/ShapeNet/ShapeNetCoreV1/render_depth.py", line 76, in setup_blender
>     bpy.data.objects['Cube'].select = True
> AttributeError: 'Object' object has no attribute 'select'
> ```
> 
> What's the version of the Blender you used?

In the latest version, you can use 'bpy.data.objects['Cube'].select_set(True)'.
